name: "DEVKING_RELEASE"
inputs:
  repo-token:
    description: 'REPO-TOKEN'
    default: 'REPOTOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash      
      #run: echo ; echo "OS = `uname -a`" ; echo "NODEJS = `node -v`" ; echo "NPM = `npm -v`" ; echo ; cd ${{ GITHUB.ACTION_PATH }} ; pwd ; echo ; npm ci ; echo ; cd ${{ GITHUB.WORKSPACE }} ; pwd ; echo ; export GITHUB_TOKEN=${{ GITHUB.TOKEN }} ; export FORCE_COLOR=1 ; node ${{ GITHUB.ACTION_PATH }}/action.js
      run: export FORCE_COLOR=1 ;  export GITHUB_TOKEN=${{ GITHUB.TOKEN }} ; cd ${{ GITHUB.ACTION_PATH }} ; echo "OS = `uname -a`" ; echo "NPM = `npm ci`" ; cd ${{ GITHUB.WORKSPACE }} ; node ${{ GITHUB.ACTION_PATH }}/action.js --loglevel trace