name: "DEVKING_RELEASE"
runs:
  using: "composite"
  steps:
    - shell: bash      
      run: export FORCE_COLOR=1 ;  export GITHUB_TOKEN=${{ GITHUB.TOKEN }} ; export NEXTVERSION=${{ github.event.inputs ; cd ${{ GITHUB.ACTION_PATH }} ; echo "OS = `uname -a`" ; echo "NPM = `npm ci`" ; cd ${{ GITHUB.WORKSPACE }} ; node ${{ GITHUB.ACTION_PATH }}/action.js --loglevel trace